### PR TITLE
(WIP) Album Art Overhaul and New Genres

### PR DESCRIPTION
**Pull request by exoticri**
This mainly focuses on replacing old art scans with newer ones that don't appear damaged and to remove the Parental Advisory warning on some old scans.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Don't forget to define animation genres for the new genres.

**Comment by jnackmclain** [comment]
Be done already I have 2 pr's to song updates :)

**Comment by jnackmclain** [comment]
No wait 3
:>)

**Comment by jdk13** [comment]
I wanna play Alone with the homies :(((((

**Pull request merged**
