### PR TITLE
ataeaf's rb4 bass solo updates

### PR DESCRIPTION
**Pull request by exoticri**

### CODE REVIEW

**Comment by r0bd0g** [comment]
something is still weird about the knights of cydonia keys tracks

**Comment by r0bd0g** [comment]
They're in a strange order, and it lists bass twice. I'm not sure how the yarg song_updates has ended up looking normal though.

**Comment by jnackmclain** [comment]
is it good now? lol

**Comment by jnackmclain** [comment]
need to regenerate songs updates again for safety

**Pull request merged**
