### PR TITLE
Allow's GoCentral to write in the % value

### PR DESCRIPTION
**Pull request by Cloudsify**
image

### CODE REVIEW

**Comment by jnackmclain** [comment]
How does this allow go central to write here? this seems like it may have unintended side effects as it is claiming every score is a high score

**Comment by Cloudsify** [comment]
Originally it would only show 1% if that value wasn't changed even tho GoCentral was setting it in this case 69420

**Comment by jnackmclain** [comment]
Right but looking at the code, this variable is set when the player actually sets a high score. it is only used in 3 places, one of which plays a sound.
image
image
image

**Comment by Cloudsify** [comment]
Ah, I see. Did Just set a score lower and it was somehow a "high score". It was the only way though I could get the game to register a different value

**Comment by jnackmclain** [comment]
Yeah that's what i'm saying, with this change every score is a "high score"

**Pull request merged**
