### PR TITLE
Wii texture support

### PR DESCRIPTION
**Pull request by qfoxb**
Working on adding Wii texture support. Included is a python script to convert from a TPL to a png_wii file. 
Not implemented in configure_build.py yet.

### CODE REVIEW

**Comment by DarkRTA** [comment]
In order for this to have any chance of getting merged such a tool will need to natively run on both Windows and Linux.

Depending on C# is annoying but acceptable right now, but we absolutely should not depend on the monstrosity that is Wine.

I'd also prefer if you write the tool in rust without a dependency on wiimm's tools. Those tools are open source so you should be able to study them and figure out the texture format.

As an alternative to that, you may opt to write a seperate tool in python that fixes the header after converting with wiimm's tool. Ninja is more than capabale of dealing with that and we already use a similar setup for PS3 textures.

**Comment by qfoxb** [comment]
I can 100% put Mac and Linux binaries just didn't get the chance to last night because it was 2AM lmao

no mono or wine involved

**Comment by qfoxb** [comment]
Switched from C# based PngWiiTool to a python tool I just cooked up that does the tpl -> image.png_wii part. PNG to TPL will be handled directly in configure_build.py

**Comment by qfoxb** [comment]
Wiimm's tool can't do alpha properly. Closing PR.

**Pull request closed without merging**
