### PR TITLE
Visual Update with new Rock Band 4 gems, smashers, highways and spotlights

### PR DESCRIPTION
**Pull request by berthrage**
Hello there, I have created new revamped Rock Band 4 gems and smashers to match RB4 colours and visuals better. 
If possible I would like to continue revamping more of the textures, but then I'll need more custom textures to be added: the biggest priority for me is the Multiplier Circle (to add the golden outline and blue circle background) and the colours of the sustained notes (which I wanted to change the blue to a lighter tone to better match RB4 too). I also wanted, if possible to be able to add more Smashers options in the menu (beyond RB2, RB3 and RB4, ie: a 'Goth' looking smasher or something like that).

New Highways and Spotlights have been added as well and they suit the game rather well.

I have included the PSDs as well, even though I reckon they shouldn't be distributed with rb3dx (but they can be edited out of course). Feel free to utilise them if so desired. My intention is to keep bringing some of these visual enhancements to the game as much as I can.

### CODE REVIEW

**Comment by berthrage** [comment]
Preview of the changes: https://imgur.com/gallery/At6wedf
New Goth streak: https://imgur.com/gallery/pmP5THu

**Comment by LlysiX** [comment]
Not a big fan of the smashers, they don't look much better, just overexposed/oversaturated. The opposite is true of the gems.
The upscaling of all of the textures is not the best and is also likely to overload consoles, especially while running with animated textures.

Highways look pretty neat! toss them into #highways-spotlights-emissives in the [discord](https://discord.gg/xrba4CjdNC), might even add them in if they were in their own PR!

As for adding new smashers/gems/etc, the setup for those needs to be reworked as the current method requires a lot of manual editing of dtas (and the current texture processing scripts are a bit broken). Once that is done, other new texture options can be added and changed quite easily with the help of new menus and minor dta changes, but I'm a bit worried customization could get too overwhelming if we add too many options.

Your first preview link goes to a 404 page lol

**Comment by berthrage** [comment]
New preview: https://imgur.com/a/SJwGTUN 
sorry for the 404

About the oversaturation/exposure, I can see why you wouldn't like them. But they're very very similar to what Rock Band 4 offers and I would argue that staying true to it is better in a way, or at least giving more options to players, people may like these. Also I disagree a bit about overwhelming with options, as rb3dx is made for increasing customization options, not reducing them.
It's oversaturation/exposure there is because of the way RB3 renders the texture, which is way darker than the texture itself

And thanks! I'll for sure post these in the discord!

**Comment by jnackmclain** [comment]
Is this fully up to date ready to merge?

**Comment by berthrage** [comment]
Everything is ready to go. Though some adjustments will prolly have to made. I've used on_extend extensively in order to load the new textures, which I know isn't ideal, but I don't have enough .dta knowledge to properly integrate them into the menus system. Two considerations I'll add:
-I've left additional files, one for an extra "sunset" rail, which looks really really cool. Please add the option to change to it as well, if possible, it has a cool looking gradient effect that I know people will enjoy, several of my early screenshots used an outdated version of the rail, and it was well received back then.
-The other additional file is for an extra flare effect with a star on it, some people may enjoy, some may not, I'd consider keeping it as an option as well if possible.

I tried not replacing any of the existing highways or spotlights. But if you see that it becomes too overwhelming along with the old ones feel free to replace the old ones, I just didn't have the courage to do it.

**Comment by berthrage** [comment]
Also, I've upped the res to 2x on the multipliers and the Guitar Smashers, please experiment with it and see if it runs properly on OG hardware. 2x on them looks waaaaay better, like night and day difference. But if anything goes wrong, I can downsize it.

And the RB4 sustain trail fx are currently replacing the RB2 ones, as left in the comments.

**Comment by jnackmclain** [comment]
Sorry we have decided not to merge this PR

**Pull request closed without merging**
