### PR TITLE
fix and add song key info

### PR DESCRIPTION
**Pull request by SonicSBL**

### CODE REVIEW

**Comment by jnackmclain** [comment]
This PR is inaccurate. Songs_updates.dta is not actually used by the game. that file is generated by the game ffor use to upload with yarg song updates. You need to add them to the metadata updates dtas in the folder. @exoticri do you have a specific preference on that?

**Comment by exoticri** [comment]
sorry for late response, but please revert your changes to songs_updates.dta and add these updates to the official_additional_metadata.dta

**Comment by SonicSBL** [comment]
I think I got it right now.

**Comment by exoticri** [comment]
yep everything's in the right place now

**Pull request merged**
