### PR TITLE
fix rbn/dlc issues and make locale/metadata changes

### PR DESCRIPTION
**Pull request by exoticri**

### CODE REVIEW

**Comment by r0bd0g** [comment]
Nit: UGC_5003300 should be moved below the 'no harmonies' comment.

This one was a recent edit in that thread, but it's also dumb so you might have seen it and opted not to fix it.
"beethovensc - The first couple of beats on Medium I think might have the wrong drum mix? It's drums0 instead of drums1 like the rest of the difficulties. Seems to be a vanilla issue. I think the intention was likely drums1easynokick?"

I'd like to see a restoration of UGC_5003677 (Boney Mean - The Ending Is Death)'s pro drums someday. So I recommend trying to find somebody to put doing that on their to-do list idk. I glanced at the chart and it looked terrible so it's probably beyond me to actually fix that. Hihats on mixed in on yellow throughout on a disco flip song or some shit.

After this gets merged should I just DM you anything else I notice on discord? I hope there aren't too many weird issues in the official DLC updates... I've only just started on the official songs though. This is a months-long project for me.

**Comment by exoticri** [comment]
yeah dms would actually be better now that you mention it

**Comment by r0bd0g** [comment]
tomsawyer2 - apparently you need a 2nd copy of the easy pro keys chart
redbarchetta - ditto
yyz - yep
jokerandthe - same thing

**Comment by jnackmclain** [comment]
Thank you both for your diligence

**Comment by Bakartridge** [comment]
Found a new issue, The Ultimate Showdown's (UGC_5003146) update crashes the game when attempting to play it. Tried playing on guitar and the game crashed, probably happens with the other instruments too.

**Comment by jnackmclain** [comment]
@exoticri just ensuring you saw this

**Comment by exoticri** [comment]
@Bakartridge mightve been a one-time thing on your end, just played it on guitar fine

**Comment by Bakartridge** [comment]
Probably, gonna test it later

**Pull request merged**
