### PR TITLE
Apply RB4 RBN updates

### PR DESCRIPTION
**Pull request by EafAtta**
Apply updated from RB4 RBN releases into RB3DX
Includes midi updates, and metadata updates (difficulty and genre changes) 
Does NOT include section names, as the game does not read those properly (the percentage sections from the base midis are used in the selection practice section screen, but the updated markers are used in other places) 
The For the Love of God (Live) BRE is added, as the game does read the EVENTS when the track is loaded 
In the case of pre-existing update files some cases, if the reported difference was negligible (e.g. a note is one tick off) I just left the existing update file alone. 
Stuff like harmonies (that weren't used in the RB4 versions) and pro keys/strings upgrades have been taken into account

### CODE REVIEW

**Comment by r0bd0g** [comment]
New track in update: 'creepydoll_rbn'
New track in update: 'howwedlookonpaper_rbn'
New track in update: 'whatsyourfavoritedinosaur'
New track in update: 'littleblackbackpack_rbn'
New track in update: 'kicksomeass09_rbn'
... probably more.

Likely weird extra track names that will confuse YARG?
Actually taking a look inside the midi, I don't actually see these tracks or weird track names? So I dunno what the deal is. I'm guessing it's probably fine, since I don't actually see those tracks anywhere in the midi? Just at a glance this difference looked like a duplicate track name issue that would confuse yarg from time to time.

**Comment by r0bd0g** [comment]
UGC_5000990 had drum mix events updated in this PR, but drum mix 3 was correct. Likely RB4 used a different mogg then? So the drum mix event changes should be changed back to the correct mix type (might not always be straight forward depending on exactly what was changed), but you might need to give songs like this one a closer look to make sure all the updates make sense since it seems like RB4 used a different mogg.

I'm seeing where other songs are likely affected in the same way. You'll want to go through any other songs with updated mix events and confirm the original mix type was correct for the original RBN release (I think it's likely that the original mix type was correct across all affected songs).

**Comment by r0bd0g** [comment]
[I haven't checked if this is something that was changed by this PR.] UGC_50001277 (Ikea) used to have a vocals track update that adjusted the position of overdrive markers in order to work around the RB3 harmony overdrive bug. I'm not sure where this update has disappeared to or how serious the issues might be if it remains removed (I worry it could result in some phrases giving extra overdrive when they shouldn't). There might be other songs where a vocal track update for this purpose has gone missing? I did find another instance where the vocals track could have been accidentally removed, but I think it was still there, unless those were just unrelated RB4 adjustments. Another song that's awkward is Creed's "Higher". I think some overdrive markers were adjusted on solo vocals in that song, and I think those adjustments are missing now? But that song might have actual chart differences maybe, on solo vocals according to the difference? So in theory one ought to apply those changes to the harmony vocals as well?? I'm pretty confused by it all. It's rough out there.

**Comment by r0bd0g** [comment]
You cannot update harmonies tracks in songs that have harmonies in their main midi. Due to a bug in RB3, these harmonies updates replace solo vocals instead. So any songs that have harmonies already you need to remove any harmony updates.

(If the song also has a solo vocals update, be careful if it adjusts overdrive or phrase markers? If those get out of sync with harmonies you may or may not run into issues with the RB3 harmony overdrive bug.)

**Comment by r0bd0g** [comment]
If RB4 doesn't support pro keys, why is there a pro keys update to UGC_5007842, hey there mr brooks (rb3 version)? (I assume it's the RB3 version b/c I couldn't find the non-RB3 version's UGC number on short notice.) It probably should be ignored as garbage data? But if you want to keep it, make sure you test that the updates actually work, and test on all difficulties, because I don't think PK has ever been updated like this before, and PK updates are known to be a bit fickle to get working correctly.

That's all the weirdness I was able to spot quickly glancing through. Sorry if all of this was kind of harried and confusing.

**Comment by EafAtta** [comment]
> New track in update: 'creepydoll_rbn' New track in update: 'howwedlookonpaper_rbn' New track in update: 'whatsyourfavoritedinosaur' New track in update: 'littleblackbackpack_rbn' New track in update: 'kicksomeass09_rbn' ... probably more.
> 
> Likely weird extra track names that will confuse YARG? Actually taking a look inside the midi, I don't actually see these tracks or weird track names? So I dunno what the deal is. I'm guessing it's probably fine, since I don't actually see those tracks anywhere in the midi? Just at a glance this difference looked like a duplicate track name issue that would confuse yarg from time to time.

Alright, added the suggestions you posted (minus the [shortname]_rbn track, that's just an issue with how the update checker I use processes some midis and doesn't seem to make any difference in RB3DX or YARG.

Aside from keys, only HARM was updated for Hey There Mr. Brooks (which is based on the RB3 version), so I just tossed the update out completely.

Most of the HARM updates were just simple tick offsets, so not many major losses. That being said, there were some notable differences on harmonies in RB3 vs. RB4

The following are missing overdrive on the HARM1 track
Hey There Mr. Brooks (RB3 version) [UGC_5007482]
Pray for Plagues (UGC_5006665)
Stand for Something (UGC_5007127) [this one didn't seem to have any real differences between solo and HARM1, so maybe this could be kept? I removed it, regardless]
Selkies (UGC_5008010)

These two tracks have these weird slide notes on the same pitch on HARM2, that get reduce to single notes in the RB4 chart (not sure if HARM2 causes the bug, but it doesn't make a major impact on gameplay]:
A Prophecy (RB3 version) [UGC_5007485]
Shizuku (UGC_5011638)

Sick, Sick, Sick (UGC_5006194): This one has several note changes actually. Since this is RB3 era, and the PART VOCALS does include vocals from HARM2 and HARM3, I can't incorporate the HARM tracks unfortunately. I also removed the PART VOCALS for the sake of consistency.

Back Through Time (UGC_5009265): Both the PART VOCALS and HARM1 tracks have extra overdrive phrases in the RB4 chart. Some of the phrases were longer in the PART VOCALS chart in RB4 as well. (Both tracks were removed from the RB3DX update mid for consistency)

Creed - Higher (UGC_5002868) did have the updated PART VOCALS integrated into HARM1 as well (as it was really simple to do) and the overdrive phrase adjustment was added back in. Drowning Pool - Bodies (UGC_5001770) also has a PART VOCALS update, but I haven't added that into the harmonies (as there's a bit more work to that. Though at least there's no overdrive phrase conflicts.

**Comment by r0bd0g** [comment]
I wanted to apologize in advance for the length of this post. Most of it is just me rambling; very little actual important information lol.

It doesn't make sense to keep any harm 1/2/3 update to an existing harm 1/2/3 b/c it fails to actually update harm 1/2/3; any harm 1/2/3 update always only updates solo vocals. (There's a potential exception where it might make sense? But don't actually do this. We're not actually doing this. In theory, on every song with a harmonies update, we could maybe include a harm 1/2/3 update, and then always include the full solo vocals track LAST in the midi, and what that would do is, add harmonies if they don't exist, but if they do exist, it will encounter the solo vocals update last and so that will be the final track to update over top of solo vocals. And this could guard against screwing up the solo vocals chart for any players that might have manually added harmonies updates to their songs. That's the only reason I could think of to update a harmonies chart that already exists, and it's 'maybe they don't actually already exist'.)

Those songs which lack overdrive phrases on harmonies -probably- work fine in RB3 (maybe somebody ought to check just to make sure) because the harmony overdrive bug is gonna apply the solo phrases to harmonies anyway. It's just after they fixed that bug in RB4 that legacy songs needed to be updated to have actual overdrive on harmonies. (I wonder if, all this time, we should actually not have been authoring overdrive on harmonies in harmony updates for RB3. I wonder if removing them would cause no issues while reducing the unison bonus desyncs when playing with players that don't have the harmony updates? But this idea has never been tested. Don't actually do this, I'm just musing.)

No actual relevant information in this paragraph, but I wanted to talk about about slide notes to the same pitch - they actually work? And they can be used to serve an actual purpose. You can notice the slides to the same note in gameplay in some cases. Each pitch tube has a maximum amount of the "pie" (this is what I call the circle that fills as you hit notes) that the player is allowed to fill (I call this "pie filling") before the end of the tube. If you put a slide to the same note, this causes this effect to occur in the middle of a single tube (as in, if you sing well, the pie might stop filling in the middle of the tube, until the position where the slide secretly occurs, and then the pie will start filling again). I THINK there is a glitch with how the 'maximum about of pie filling' affect works if a pitch tube crosses a phrase divider. I think the pitch tube, being the final pitch of the previous phrase, allows you to potentially fill the entire pie, and this pitch tube being uncapped in how much pie you can fill continues into the next phrase, potentially allowing you to cheese the new phrase a bit by just singing the first note very well. I hope I wasn't too confusing with that explanation. But anyway, when I author a pitch tube across a phrase marker like this (and some of my RBN harmony updates do include this trick), I attempt counteract this cheese issue by authoring a 1 tick gap around the divider and using a slide to the same note, to hopefully reset the cap on the pitch tube into the new phrase. (Even if it doesn't do what I want, it doesn't seem to break anything, lol.)

You may be able to include the solo vocal update to back through time. It will depend on exactly where the overdrive and phrase dividers land, whether glitches occur that might offer extra overdrive than was intended. But you'd have to very carefully look over the song to see if there is potential for issues arise. It's honestly probably not worth the trouble. (And maybe adding overdrive like that could maybe be a bit more intrusive than we'd like an update like this to be?) (Fun fact, the current 'score snipe' song, official RB3 DLC "Unbelievable", falls prey to the harmony overdrive bug. A phrase marker ending earlier on harmonies causes a phrase with only half the words lit up to award an extra energy than you would get on solo vocals. So sometimes having broken harmony overdrive is maybe not the end of the world, but better to not break anything if we don't have to.)

This is a list of harmony upgrades that I authored where I did use minor solo vocal overdrive adjustments. Some of them, we talked about already. I don't know how many of them made it into RB4, but if they did, can you check on them to see if the adjustments are still in? (I remember before starting on making these that I saw one harmony upgrade with a solo vocals update that had recently been added, I dunno what changes were made, but I took inspiration from that and just went ahead and tweaked solo a bit. I don't remember what song this was or who authored it or if it made it into RB4.)
Higher, Ikea, Rise Above This, Shop Vac, and Whatever Happened to You.

Glancing through the changes, I wanted to point out that htmlrulezdood_rbn had a change to the character animations in the drums text events (an [intense] was added). So in some cases you might want to merge the text events between the original and the rb4 update. On lexington_rbn, the text event change to dnoflip might make sense, I haven't checked, so I just wanted to ask about it. You would typically use that for a disco flip section with snares on yellow and maybe toms (rather than cymbals) on red. So you'd want to check what's going on there in the actual song before reverting that change. It's cases where the mix -number- was changed where we most likely ("most likely" because in theory the original RBN charter could have used the wrong mix events, but it might not be worth the trouble to check on that) don't want those changes.

**Comment by EafAtta** [comment]
Oh, since you mentioned overdrive updates, there are quite a few songs that have overdrive added or removed on the 5-lane charts. Should I just keep the original RBN overdrive in those cases?

Also, Lexington (UGC_5005213/lexington_rbn), the disco flipped section has the snare on red. (Not sure why it was needed, since red is normally snare on non-disco sections.) It was a normal disco flip event in RBN (since the dnoflip event didn't exist in RB2) and changed to dnoflip for RB4. In fact, in the RB4 chart, after the section ends there's a garbage "drums0noflip" (not drums0_d_noflip) event on hard. I did keep the dnoflip events but fixed the broken event.

For the record, Rise Above This does have the adjustment retained in my RB3DX update, and the other two songs (Shop Vac and Whatever Happened to You) you mentioned weren't brought over to RB4.

**Comment by r0bd0g** [comment]
OK if the snares are on red there should be no disco flip event at all. The main reason those events exist is make the yellow count for more rock meter, or to tie the snare stem(s) to yellow if applicable. Snares on red means you don't want either of those things.

I'm not sure what to do about that kind of overdrive overhaul. It's a bit of a can of worms because online play will get pretty weird between players who have the updates and don't. That already happens a bit from added charts breaking unison bonuses, but this'd be the first time you'd see it where overdrive is in different places between the already existing charts... I could image it'd get particularly weird if the unison bonuses have been moved around? Hard to know how that would play. But one assumes the new overdrive placement is probably more balanced overall? Keys updates will probably have their overdrive based on the original RBN's overdrive placement, so if any song has moved overdrive and a keys update, you might have to author new keys overdrive, to make keys join the new unisons and to avoid creating unintentional new unisons. It's probably safer to keep the original overdrive placement except maybe very minor tweaks/fixes if those exist, especially with that potential complication of needing to reauthor a keys upgrade's overdrive. Maybe ask what others think idk.

**Comment by EafAtta** [comment]
Yeah, I've decided it's better to just keep the original overdrive placements. I'll also get rid of the dnoflip event on Lexington

**Comment by EafAtta** [comment]
Actually, I just realized that For The Love of God has a drum overdrive marker that gets removed because RA decided to place a BRE over the ending for the RB4 chart that wasn't in the original RBN chart. I probably shouldn't include the BRE then.

**Comment by EafAtta** [comment]
Restored all of the original od placements (Young Bloods also had some drum fill changes that I reverted). Mostly not major losses. One thing that was lost was ShadowBang (Head) (UGC_5002292) which had drum fills added to the RB4 chart (in the original chart, they're just straight up missing), and the guitar/bass od phrases are moved around to account that. Part of me wanted to break this rule just to add the fils/od back in, but I decided not to. Mechanical Love does have vocal od phrases readjusted, but there was just too much that would have needed to be changed. They're all in relatively the same positions, so I figured it'd be fine to leave them as is.

**Comment by EafAtta** [comment]
Restored the original fill sections

Also Between the Buried and Me - Mordecai (UGC_5001352/mordecai_rbn) had some grid snapping issues in the RB4 port that I fixed

**Comment by EafAtta** [comment]
One thing I noticed is that the guitar solo for Young Bloods (UGC_5001927/youngbloods_rbn) is rather different on guitar in RB4 compared to the RBN chart? What should I do in this case? I know the RB4 version of Through the Fire and Flames was made into a separate custom, but that song is a lot more famous. I'm actually leaning toward using the RB4 chart in the RB3DX update tbh.

**Comment by r0bd0g** [comment]
If the ttfaf update doesn't currently apply the rb4 chart, I wasn't actually aware of that lol.

**Comment by jnackmclain** [comment]
yeah rb3 ttfaf is preserved as a special case due to the significant recharting

**Pull request merged**
