### PR TITLE
Song Keys!

### PR DESCRIPTION
**Pull request by Moose1002**
### Song Keys are here!
I've added a new song.dta attribute `song_key (key)` that allows custom makers to define the key their song is in, to be shown in game. A few of my friends that play piano professionally commented that knowing the key the song is in before they start playing pro keys, would make it much easier to know which notes chords would make up, thus just making the whole experience better (at least that's my understanding of it, I'm not a keyboard player).

Also to go ahead and get some keys in there, I've added song keys to every Rock Band 1, 2, 3, Lego, and Greenday songs, as well as all of those game's DLC. These keys are taken from Spotify using a python script that takes a .setlist file and finds the song keys of every song in that .setlist, so if any don't look right blame Spotify, and help me fix them! Also if wanted I can add that python script wherever requested if more mass song keys need finding, so feel free to ask.

### In Game Examples
A Song in a Major Key:
SongKey1
A Song in a Minor Key:
SongKey2
A Song With No Key Defined:
SongKey3

This is my first PR to the repo, and my first time doing something big with .dta, so if anything looks wrong or needs changing please let me know! Thanks!

### CODE REVIEW

**Comment by jnackmclain** [comment]
I'm going to leave merging and checking this in charge of @LinosM 
Very cool stuff!

**Comment by Moose1002** [comment]
Thanks Jnack! Huge fan of Rock Band 3 Deluxe! Hoping to contribute more in the future.

**Comment by LinosM** [comment]
Hey there this is pretty cool stuff, though I should mention there is already existing metadata that shows the Key of the song in Pro Trainers

Notably vocal_tonic_note and song_tonality, song_key is also an already existing field RB3 uses should you need to override the vocal key

RB3 era songs should already have this information and DX adds it to majority of legacy songs already which can be found in this file
https://github.com/hmxmilohax/rock-band-3-deluxe/blob/develop/_ark/dx/song_updates/official_additional_metadata.dta

These numbers for vocal_tonic_note correspond to what Key and song_tonality 0/1 determines major/minor respectively.

image-15

If you're able to rework the script to show the Key based on these values that'd would be much appreciated 👍

**Review by DarkRTA — CHANGES_REQUESTED** [review]
I have to agree with Linos here. Use the metadata we already have instead of creating an entirely new field that serves a similar purpose to an existing one.

**Comment by r0bd0g** [comment]
I want to say in my experience the internet is wrong about the key of the song about 75% of the time. I really don't trust spotify on this. (We've got a handful of them wrong too though.) You probably have to listen to the songs and judge what you think the key is yourself, time consuming.

**Comment by Moose1002** [comment]
Alright, song_key.dta has been removed and `vocal_tonic_note` and `song_tonality` are now used to determine the song key. Still looks idenetical to the screenshots as I'm still using localization to format the strings, but if y'all would rather me do this some other way I'm happy to.

**Review by DarkRTA — APPROVED** [review]

**Comment by DarkRTA** [comment]
linos would you mind taking a quick pass over this in case i missed something

**Comment by r0bd0g** [comment]
Remember song_key's original purpose. If it's set it should override vocal_tonic_note.

**Comment by Moose1002** [comment]
Oops, completely forgot about that, should be fixed now. I also added "Key of:" before the key of the song to make it more inline with how it's done in the pro-trainer. Should be good to go now!

Updated Screenshot:
(I changed it to "Key of:" rather than "Key Of:" as that's what the pro-trainer has, the screenshot was taken before that change)
image

**Comment by LinosM** [comment]
I was going to bring up song_key as well but I see that has been addressed. Everything else seems good.

**Pull request merged**
