### PR TITLE
Added all rbhp rbn pro drum fixes

### PR DESCRIPTION
**Pull request by iamSynchrony**

### CODE REVIEW

**Comment by iamSynchrony** [comment]
hi you guys forgot to merge my pr

**Comment by jnackmclain** [comment]
Waiting for review from @exoticri

**Comment by Cloudsify** [comment]
> hi you guys forgot to merge my pr

Sorry to but in here but, People have lives you know and don't involve around a game that contains plastic instruments. Instead of commenting what you said, can you not just wait?? Plus I don't think they forgot to either, it's just a chance that they have gotten around to doing it. So please be patient thank you :)

**Comment by iamSynchrony** [comment]
my bad it's just that other more recent prs were merged before mine

**Comment by Cloudsify** [comment]
No worries, It's most likely because exoticri hasn't be available 🤷🏼‍♂️

**Comment by jnackmclain** [comment]
It was merged before because that pr changes 2 lines and yours changes almost 600 files

**Comment by exoticri** [comment]
i cannot test your changes because your build doesn’t even boot the game

**Comment by iamSynchrony** [comment]
it works fine for me on rpcs3

**Comment by exoticri** [comment]
well i’m not using emulator
i’m using real 360 hardware

**Comment by iamSynchrony** [comment]
i haven't changed anything that could make the game not boot so i have no clue what could cause that

**Comment by ieee802dot11ac** [comment]
you might not have, but that doesn't change the fact that it's broken
fix it. i know you have an RGH

**Comment by iamSynchrony** [comment]
i'll look into this then

**Comment by iamSynchrony** [comment]
alright i looked through everything and have genuinely no clue what's causing it

**Comment by jnackmclain** [comment]
I can confirm your branch doesnt boot in xenia either

**Comment by jnackmclain** [comment]
also try rebasing your branch off develop

**Comment by jnackmclain** [comment]
image

**Comment by jnackmclain** [comment]
I have found the problem for xbox and it's no ones fault.
This commit brings the total number of folders in the "updates" folder to 2161.
I have found if it has an item count greater than 2096, the game will not boot on xbox.
It does not seem to be the mids, rather an item count issue

**Comment by jnackmclain** [comment]
I resynced this branch but it does not resolve the crashing

**Comment by jnackmclain** [comment]
Lysix pointed out, and i was able to somewhat verify already
we are actually right at ark limit, not a limit of the folder
if i made a folder called _missing in the ark with the remaining files, it would not boot. I had to move them to the dependencies folder for now
We are actually at a hard ark file limit i believe

**Comment by jnackmclain** [comment]
the PR now boots at least, remaning rbn dta adjustments have been moved to rbhp_rbn_fixes_missing.dta
remaining midi files for these songs are in dependencies/_missing_rbn_mids/
We need to reevaluate next steps and what to do to midigate our file problem

**Comment by jnackmclain** [comment]
Yeah okay it is definitely not a folder limit, 1000% just an ark file limit.
disregard previous comment
all songs are in now. @exoticri PR is ready to be checked and approved

**Comment by r0bd0g** [comment]
Which limit exactly? Filesize limit of the entire ark? Number of files limit for the entire ark? But it's xbox only?

**Comment by jnackmclain** [comment]
Number of files inside the ark and yes apparently only an Xbox issue. Lysix said he had the same issue.
All I did was delete some images unused by dx and it booted again

**Comment by r0bd0g** [comment]
This feels like a pretty serious problem for the future. More updates are probably gonna get made eventually, right?

**Comment by jnackmclain** [comment]
Again:
> We need to reevaluate next steps and what to do to midigate our file problem

**Comment by r0bd0g** [comment]
Sorry yeah, I missed where you said that. Hopefully you'll be able to figure something out.

(I did a quick test on Wii if anybody's curious idk. I added 3000 blank files and booted up Dolphin without issue. Too much extra trouble to check on console, so we're just gonna hope it's fine.)

**Comment by exoticri** [comment]
finally getting around to testing it
tested demon woman on harms and it crashes the game
buried cold has no yellow cymbal

**Comment by exoticri** [comment]
so it seems if a song has both a harms upgrade and a pro drums upgrade it crashes the game if you select harms, however selecting pro drums only seems to work just fine

**Comment by r0bd0g** [comment]
Jnack moved some updates out of the updates folder and into the main songs folder. Could that be a problem?
(Might also mean the hypothetical limit to the number of files in a folder has not actually been tested?)

**Comment by exoticri** [comment]
no because i didn’t test the songs that he moved out, the songs that i tested were still in the updates folder

**Comment by iamSynchrony** [comment]
i'll look into the issue with songs that have harms and pro drum upgrades but i don't recall anything like that happening in my testing

**Comment by r0bd0g** [comment]
Buried Cold's drums chart looks fine to me? Plenty of yellow cymbals and toms both. Strange...
(Dumb question but was your cymbal enabled? If it was then I dunno how to explain that, super weird.)

**Comment by jnackmclain** [comment]
> Jnack moved some updates out of the updates folder and into the main songs folder. Could that be a problem?
> 
> (Might also mean the hypothetical limit to the number of files in a folder has not actually been tested?)

I also moved them back in on the very next commit

**Comment by r0bd0g** [comment]
There has yet been no next commit since that was done. (But if you fix it, what you just said will turn out to be true lol.)

You misread what I said. I know you moved them back, but you moved them back to the wrong place.

**Comment by jnackmclain** [comment]
well egg on my face I did totally move them back into the wrong spot
clumsy me. my bad

**Comment by jnackmclain** [comment]
Okay, so I am pretty unfamiliar with these songs but I just tried buried cold from rbn 1.0 on my xbox, it does seem to work, and as well, the intro notes are toms (I tried a commit before and they were cymbals)
I assume this is correct, but also this song doesnt appear to have harmonies, where the rb3 version in rbn 2.0 did.
I did clear my song cache

@exoticri make sure to run clean first just in case

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/55568980/57249efc-7673-4e69-8280-26b7c326b1f3

Also shout out to rbn megamix 01

**Comment by r0bd0g** [comment]
It guess it's like official dlc songs where there are rb3 versions, there are no rbhp upgrades for the rb2 versions? But I guess rbhp felt pro drums not working was buggy enough to be worth fixing anyway? Or maybe they made the pro drums before the rb3 version came out, I dunno what the timelines on that might be like. I wonder if there are chart differences between the upgraded pro drums and the rb3 version pro drums?

**Comment by jnackmclain** [comment]
No idea, I was just more pointing out the harmonies thing as from what I understand in this thread, this upgrade is supposed to have harmonies? but idk

**Comment by r0bd0g** [comment]
That song (UGC_5000484) is in the pro drums only section of the dta, so I think it's just supposed to have pro drums.

**Comment by jnackmclain** [comment]
Gotcha, makes sense, then for me, this one is working

**Comment by iamSynchrony** [comment]
> finally getting around to testing it tested demon woman on harms and it crashes the game buried cold has no yellow cymbal

https://github.com/hmxmilohax/rock-band-3-deluxe/assets/113392466/000a3a73-e99c-48de-8221-d252dd2c7100


just tested demon woman and it works fine for me on harms

**Comment by jnackmclain** [comment]
I can also confirm that demon woman is working for me on harms on xbox console. Not sure what is going on with exo at this point, might be good for him to pull latest action and retest it
perhaps me moving stuff in the wrong spot included that song, which would now be fixed

**Comment by exoticri** [comment]
final review
everything looks good to me

**Comment by jnackmclain** [comment]
Just curious does this also mean standing in your stuff is also fixed?

**Comment by jnackmclain** [comment]
Merged btw

**Comment by iamSynchrony** [comment]
> Just curious does this also mean standing in your stuff is also fixed?

checked and it doesn't look like rbhp fixed it

**Comment by jnackmclain** [comment]
Damn

**Pull request merged**
