### PR TITLE
Family Friendly ratings for RB2 songs

### PR DESCRIPTION
**Pull request by SonicSBL**
Because HMX never bothered to do it. Let me know if there are any other songs that would fit the description or if I did something wrong. This is my first GitHub contribution.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I looked through this a bit. I feel like in general HMX was usually pretty conservative with what was marked as family friendly? What is Linkin Park's "In The End" even about? Could be anything. Nothing obviously offensive in it. It was rated SR. You could probably find more examples like this.

A Jagged Gorgeous has the word "lust" in it.

I dunno what Aqualung is about. It has lines "Eyeing little girls with bad intent" and "watching as the frilly panties run" which at a glance don't seem family friendly to me.

Convention Lover says "And when we get to mating".

Go Your Own Way says "Shacking up is all you want to do".

Kids in America says "Come closer, honey, that's better. Got to get a brand new experience, feeling right. Oh, don't try to stop, baby, hold me tight."

Lump says "She spent her twenties between the sheets".

**Comment by jnackmclain** [comment]
Yeah id agree with Rob here for these notes. Like in no world is aqualung family friendly lol

**Comment by exoticri** [comment]
same here please ensure the encoding is corrected and saved in either ansi or western 1252

**Comment by SonicSBL** [comment]
Everything has (hopefully) been adjusted to your liking. Anything else?

**Comment by jnackmclain** [comment]
closing as it has been merged in with #857

**Pull request closed without merging**
